apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: abhyaas.dev
      http:
        paths:
          - path: /api/stats/?(.*)
            pathType: Prefix
            backend:
              service:
                name: stats-srv
                port:
                  number: 3000
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: webapp-srv
                port:
                  number: 3000
